import { ShieldAlert } from "lucide-react";

export function ResponsibleAi() {
  return (
    <div className="flex items-start gap-3 rounded-lg border border-border bg-muted/50 p-4 text-sm text-muted-foreground">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
      <p>
        <span className="font-medium text-foreground">Responsible AI:</span>{" "}
        Outputs are generated by AI and may contain inaccuracies or bias. Always
        review, verify facts, and edit before sharing. Do not paste confidential
        or personally identifiable information.
      </p>
    </div>
  );
}
